version: '3'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./chroma_db:/app/chroma_db
    env_file:
      - .env
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data: